kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm run
- name: notify
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/
